### ISSUE TITLE
The program could not be reproduced locally

### ISSUE THREAD

**Issue by Episode233** [sz3/cimbar#28]
The program could not be reproduced locally, I just renamed cimbar.py to main.py, and then used the command "python -m cimbar.main --encode input.txt qr.png" to run the encoding program, the result could not be encoded properly to get the required two-dimensional code, instead, Each square of the resulting QR code has the same content
![1](https://github.com/user-attachments/assets/db71e714-fbc0-4f6d-901a-bb6de5c99ff2)
![2](https://github.com/user-attachments/assets/76809c34-e5e6-41d5-8748-dbe581eb684d)
![3](https://github.com/user-attachments/assets/56c693c0-1f35-4832-857a-418f7d7ce014)
As shown in my picture, all the data in the stream has been read, but the program does not effectively load new data, please help me if it is convenient for you, thank you

**Comment by sz3** [comment]
Ok, so it turns out the `bitpos = (max length)` and `length = (max length)` is normal -- it means there's nothing left to read, so those counters don't get incremented. We'd need to see the early output (when bitpos is incrementing) to know if that's part of the problem.

That said, there's actually not too much going on here. (I was initially confused and was thinking it was more complicated myself...)

1. the file is opened and wrapped in a `reed_solomon_stream`. This will add 30 bytes of error correction for every 125 bytes of real data
2. the `bit_file` reads the next N bits from the reed_solomon_stream, which in turns reads the next bytes from the file.

That's actually *all* -- there's more complicated stuff going on when fountain encoding is enabled (zstd compression, wirehair...), but none of that's happening in this case. You're just getting all 0s from the file for some reason.

Some things to try:
A. a different file?
B. running the unit tests! You might need the samples for this (it's a git submodule), but you should be able to see if your local python env looks right with `python -m unittest` from the root directory.
C. your OS, python version, and dependencies might also be interesting


Final thought: it really shouldn't be necessary to rename the file from cimbar.py to main.py. `python -m cimbar.cimbar` really *ought* to work, and if it doesn't something seems strange to me.
